### ISSUE TITLE
Return Mono<Void> from ServiceInstanceWorkflow API methods

### ISSUE THREAD

**Issue by alek-sys** [spring-cloud-incubator/spring-cloud-app-broker#105]
`(Create|Update|Delete)ServiceInstanceWorkflow` classes define relevant methods with return type of `Flux<Void>` (see `update` example below) . If I understand correctly, the intention was to allow the method to *yield* in case of complex and long running actions (e.g. multiple HTTP calls, many apps to deploy etc.). However `Flux<Void>` doesn't quite follow this pattern, it basically has the same behaviour as `Mono<Void>` - only emits `onComplete` and `onError` ignoring `onNext`. Moreover, it is technically not possible to emit a value in `Flux<Void>` because the only value which can be casted to `Void` is `null` and Reactive Streams specification disallows null values in a sequence. So it feels like this API can be improved in two ways:
1. Change return type to `Flux<Something>` where `Something` can be a status or just an arbitrary object.
2. Change return type to `Mono<Void>` to avoid confusion and simplify API a little bit.

https://github.com/spring-cloud-incubator/spring-cloud-app-broker/blob/e93a0d0eb935746dc5a20ef28cecea232691b849/spring-cloud-app-broker-core/src/main/java/org/springframework/cloud/appbroker/service/UpdateServiceInstanceWorkflow.java#L25

**Comment by royclarkson** [comment]
We should consider this suggestion. Our goal is to complete one or more intermediate tasks, and perhaps returning a Flux doesn't imply that those have completed. My preference is option 2. Returning `Mono<Void>` is better, considering these injected event flows can vary greatly depending on the needs of implementing broker. Enforcing a return status may feel awkward for some of the flows or not apply altogether. As an implementer, I can complete a Flux and return a Mono<Void> on completion, so it shouldn't affect my ability to perform multiple tasks.
