### ISSUE TITLE
Backing app deployer log output might be too verbose

### ISSUE THREAD

**Issue by alek-sys** [spring-cloud-incubator/spring-cloud-app-broker#107]
When deploying backing application, log output includes `INFO` level entries for every application deployed, 

```
2018-09-16T09:27:56.52+0100 [APP/PROC/WEB/0] OUT 2018-09-16 08:27:56.515  INFO 12 --- [     parallel-4] o.s.c.a.d.BackingAppDeploymentService    : Deploying applications [BackingApplication{name='config-server', path='...', properties={}, environment={}, services=[], parametersTransformers=[...}]
```

This output includes `properties` and `environment` which potentially might include sensitive information, like passwords or SSH keys. 

I'd suggest to change backing app `toString` method to hide `properties` and `environment` completely or provide a meachanism to clean up logs output, or at least change log level to `DEBUG` (sill seems to be dangerous to me).

**Comment by scottfrederick** [comment]
@alek-sys The values in `properties` are limited to a known set of values that affect app deployment - instance count, memory, buildpack, health check options, etc. There is no security risk there. You are correct that sensitive information could be included in `environment`, and it should not be logged.
