### ISSUE TITLE
Omit or mask sensitive data in logs

### ISSUE THREAD

**Issue by habuma** [spring-cloud-incubator/spring-cloud-app-broker#127]
When attempting to update the SCS config-server with a new Git repository that requires HTTP Basic authentication, the JSON sent includes the Git repo's credentials. These are logged in plain text by `o.s.c.a.s.WorkflowServiceInstanceService` in the broker's logs.

Either the request JSON shouldn't be logged at all or it should be scrubbed to remove or mask properties with names like "password".

Here's a (manually-scrubbed with `********`) sample of what was logged:

```
o.s.c.a.s.WorkflowServiceInstanceService : Updating service instance ServiceBrokerRequest{platformInstanceId='null', apiInfoLocation='api.cf.indigo.springapps.io/v2/info', originatingIdentity=Context{platform='cloudfoundry', properties={user_id=7ec8e984-3ab7-4c78-8d7d-e3b36e2d8f2b}}}AsyncServiceInstanceRequest{asyncAccepted=true}AsyncParameterizedServiceInstanceRequest{parameters={git={label=master, password=********, uri=https://gitlab.com/habuma/test-config, username=********}}, context=Context{platform='cloudfoundry', properties={spaceGuid=e21bc29a-d346-484a-990d-85fd12302895, organizationGuid=64481248-61ac-4843-9d77-780754858a64}}}UpdateServiceInstanceRequest{serviceDefinitionId='279d22f6-7d8c-4113-9fcc-e319113aaa6a', planId='b43d9058-c163-42d3-a863-b55480c7b341', previousValues=PreviousValues{planId='b43d9058-c163-42d3-a863-b55480c7b341'}, serviceInstanceId='df20a301-7698-4f87-b05b-c5451f10097c'}
```

**Comment by scottfrederick** [comment]
The object being printed in this log example comes from Spring Cloud Open Service Broker. That project logs requests and responses in a similar manner, but at a `debug` logging level where App Broker is currently using a the `info` logging level. Using `debug` level for these tracing logs in App Broker would make the projects consistent and provide useful info for troubleshooting without exposing potentially sensitive info by default.
