### ISSUE TITLE
As a service author, I can describe in a manifest that basic auth credentials should be generated for a deployed application

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud-incubator/spring-cloud-app-broker#16]
`GIVEN` The application manifest contains:
```
spring.cloud.appbroker.apps[0].credential-providers:
  - SpringSecurityBasicAuth 
```
`AND` The application manifest contains an app named `basic-auth-app`
`WHEN` a service instance is created
`THEN` the application `basic-auth-app` has a `SPRING_APPLICATION_JSON` environment variable containing the values: 
```
{"security.user.name": "ageneratedusername", "security.user.password": "ageneratedpassword"}
```

**Comment by scottfrederick** [comment]
Fixed via https://github.com/spring-cloud-incubator/spring-cloud-app-broker/pull/115
