### ISSUE TITLE
As a service author, I want service instance creation parameters mapped to discrete env vars on deployed applications

### ISSUE THREAD

**Issue by royclarkson** [spring-cloud-incubator/spring-cloud-app-broker#19]
`GIVEN` that I specify a backing app with the name: `mapping-app` 
`AND` I specify that I want it to be a discrete env variable
`WHEN` cf create-service my-service -c '{"key": "value" }'
`THEN` I can see the property "key=value" in the environment variable for the backing app `mapping-app`.

**Comment by scottfrederick** [comment]
Fixed via 0ae92a598abd86469335d3a1a993a6efe634eee9
