### ISSUE TITLE
As a service Author I want to run acceptance tests using a suitable environment

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/spring-cloud-app-broker#45]
**Given** Environment secrets and credentials are available to the build
**When** When a build is triggered by a Pull Request in the open source project repository
**Then** The build uses a Cloud Foundry server to run acceptance tests against
**And** Does not expose any secrets in files or logs

**Comment by csterwa** [comment]
@ojhughes is this in progress?

**Comment by ojhughes** [comment]
where? (bosh-lite, BYOInstance, VM snapshot, PWS...)

Are ATs part of CircleCI or a separate thing?
Are ATs part of the same repo?
What are we going to use to code the ATs?
Are we going with the cf cli?

**Comment by ojhughes** [comment]
- [ ] Document pros / cons for above questions

**Comment by ojhughes** [comment]
Trying to create a service broker  within the AT setup but looks like CAPI cannot connect to the service broker:
```cf create-service-broker sample-broker user password https://sample-broker.mybroker.my-app.com
Creating service broker sample-broker as admin...
FAILED
Server error, status code: 502, error code: 10001, message: The service broker could not be reached: https://sample-broker.mybroker.my-app.com/v2/catalog```
I can curl the broker from my machine but not from cloud controller VM
