### ISSUE TITLE
Publish SNAPSHOT builds

### ISSUE THREAD

**Issue by AlbertoImpl** [spring-cloud-incubator/spring-cloud-app-broker#65]
Publish SNAPSHOT builds to https://repo.spring.io/libs-snapshot-local
We could do it the same way connector does: https://github.com/pivotal-cf/spring-cloud-services-connector/pull/76/files

**Comment by royclarkson** [comment]
SCS Connectors snapshots are published from bamboo. That’s the easiest way to get snapshots published for app broker.

**Comment by AlbertoImpl** [comment]
They can be found https://repo.spring.io/libs-snapshot-local/org/springframework/cloud/appbroker/
