### ISSUE TITLE
Make ComponentTests replay faster

### ISSUE THREAD

**Issue by AlbertoImpl** [spring-cloud-incubator/spring-cloud-app-broker#70]
At the moment we have to wait almost as if it was a real scenario due the way we are replaying the scenarios and the way the CF java client handles the exponential backoff.

**Comment by AlbertoImpl** [comment]
So doesn't seem to be an option out of the box in wiremock nor in the CF java client.
In wiremock, we have `ignoreRepeatRequests` but that will record only the first request (causing always to be waiting when replaying).
By default it's false and that means that it records all the requests, therefore we will have to wait almost the same time as if it was a real one because of the exponential backoff in the CF java client.
In the CF java client the backoff seems to be hardcoded, so not much room for changing that either.

Ideally, we could set the backoff in the CF java client or tell wiremock to only record the last.

**Comment by scottfrederick** [comment]
I agree that this is important to implement, as test time is going to increase as we add more component tests.

I was wondering if wiremock had something like the `ResponseTransformer` we have implemented now that could be used to inspect the payload, look for these app status calls, and throw away the intermediate requests or transform an intermediate "in progress" response to a "completed" response.

**Comment by scottfrederick** [comment]
Fixed via cd0b5c2384516d838775ab5aba06ee5d765f7f6a
