### ISSUE TITLE
Add Stateful Behaviour to Component Tests

### ISSUE THREAD

**Issue by ojhughes** [spring-cloud-incubator/spring-cloud-app-broker#72]
Wiremock supports the creation of scenarios to allow for stateful contract tests [1]

An example might be;

1. `GET /stub-b/applications ` returns []
2. `POST /stub-a/applications -d {"name": "stateful-app"}` is performed
2. `GET /stub-b/applications ` now returns `[ {"name": "stateful-app"}]`

[1]http://wiremock.org/docs/stateful-behaviour/

**Comment by ojhughes** [comment]
- [ ] How can stub recording process include scenarios. Is extra automation required?
- [ ] Will Java DSL be more readable than JSON stubs?

**Comment by scottfrederick** [comment]
@ojhughes I think the desired affect of this issue is addressed in cd0b5c2384516d838775ab5aba06ee5d765f7f6a.
