### ISSUE TITLE
As a service author, I can perform custom operations on create service

### ISSUE THREAD

**Issue by scottfrederick** [spring-cloud-incubator/spring-cloud-app-broker#81]
`GIVEN` that app broker is configured to deploy an application on create service
`WHEN` an implementing broker contributes a bean to the app context that adheres to an app broker interface
`THEN` the broker-provided bean will be invoked along with the app deployment operations provided by app broker

**Comment by royclarkson** [comment]
The level of granularity I'm working toward is to offer customizable event hooks for an overall `cf create-service` action, not for individual app deployments within that. This needs clarification if that is not the case.

**Comment by scottfrederick** [comment]
@royclarkson The intent of the story is as you described it.
