### ISSUE TITLE
Restore service-instance log proxying by using recent-log endpoints on the CF log-cache API

### ISSUE THREAD

**Issue by emalm** [spring-cloud-incubator/spring-cloud-app-broker#995]
The commit at https://github.com/spring-cloud/spring-cloud-app-broker/commit/09d4736ceb4075e0a254440d7f2c037409bb3dd7 appears to have removed the ability of this broker to proxy logs for the CF app instances that constitute the service instances that it manages. This removal was prompted by the Traffic Controller removing the recent-logs endpoint, as part of CF's transition away from the Loggregator system in favor of its [new "shared-nothing" architecture](https://docs.vmware.com/en/VMware-Tanzu-Application-Service/5.0/tas-for-vms/loggregator-architecture.html#sharednothing-architecture-2), but there are equivalent HTTP endpoints on the log-cache component that allow consumers such as the CF CLI and Apps Manager to get recent logs by app ID (or source ID, more generally). The log-cache component is expected to remain part of the CF/TAS logging architecture even as the rest of the Loggregator system is deprecated and removed over time, so its endpoints should be stable indefinitely.

More information about these log-cache endpoints is available here:
* Documentation for the log-cache HTTP API: https://github.com/cloudfoundry/log-cache-release/tree/main/src#get-apiv1readsource-id
* https://github.com/pivotal-cf/spring-cloud-gateway-service/issues/2058#issuecomment-1503308547 has an overview of the API endpoints and responses.
* https://github.com/cloudfoundry/go-log-cache is a Golang client library for the log-cache API, and is used in the [log-cache cf CLI plugin](https://github.com/cloudfoundry/log-cache-cli).

cc @mkocher @acrmp @ctlong @rroberts2222

**Comment by Albertoimpl** [comment]
Thanks a lot for all the information. 
Fixed by [ca6f4278e4cfcf7a5e75adec9efdaa89151e6fc4](https://github.com/spring-cloud/spring-cloud-app-broker/commit/ca6f4278e4cfcf7a5e75adec9efdaa89151e6fc4)
